apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mvn-exec
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to use
      default: maven:3.8.8-amazoncorretto-21
    - name: COMMAND
      type: string
      description: The Maven command to run
  workspaces:
    - name: source
      description: The workspace containing the Maven project
    - name: cache
      description: The workspace for the Maven cache
      optional: true
  steps:
    - name: run-maven-command
      image: $(params.IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        # check if the cache is mounted
        if [ "$(workspaces.cache.bound)" = "true" ]; then
          echo "Cache found, using it..."
          mvn -Dmaven.repo.local=${WORKSPACE_CACHE}/.m2/repository $(params.COMMAND)
        else
          mvn $(params.COMMAND)
        fi