apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: {{ include "backend.name" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: {{ include "backend.name" . }}
  template:
    ref: {{ include "backend.name" . }}