apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
spec:
  description: >-
    This Task builds a Dockerfile with kaniko and pushes the resulting image to a registry.
  params:
    - name: IMAGE_NAME
      description: Name of the image to build.
    - name: IMAGE_TAG
      description: Tag of the image to build.
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
  workspaces:
    - name: source
      description: Holds the context and Dockerfile
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
  steps:
    - name: build-and-push
      workingDir: $(workspaces.source.path)
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=$(workspaces.source.path)/$(params.CONTEXT)/Dockerfile
        - --context=$(workspaces.source.path)/$(params.CONTEXT)
        - --destination=$(params.IMAGE_NAME):$(params.IMAGE_TAG)
      # Ensure kaniko runs as root, "securityContext" is required for platforms like OpenShift.
      securityContext:
        runAsUser: 0
