apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko
  labels:
    {{- include "tasks.labels" . | nindent 4 }}
spec:
  description: >-
    This Task builds a Dockerfile with kaniko and pushes the resulting image to a registry.
  params:
    - name: IMAGE_NAME
      description: Name of the image to build.
    - name: IMAGE_TAG
      description: Tag of the image to build.
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
  workspaces:
    - name: source
      description: Holds the context and Dockerfile
  steps:
    - name: build-and-push
      workingDir: $(workspaces.source.path)
      env:
        - name: REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.dockerConfigSecret }}
              key: username
        - name: REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.dockerConfigSecret }}
              key: password
      image: gcr.io/kaniko-project/executor:latest
      script: |
        #!/bin/sh
        set -e -x

        AUTH=$(echo -n "${REGISTRY_USERNAME}:${REGISTRY_PASSWORD}" | base64)
        echo '{"auths": {"https://index.docker.io/v1/": {"auth": "'$AUTH'}}}' > /kaniko/.docker/config.json

        kaniko \
          --dockerfile=$(workspaces.source.path)/$(params.CONTEXT)/Dockerfile \
          --context=$(workspaces.source.path)/$(params.CONTEXT) \
          --destination=$(params.IMAGE_NAME):$(params.IMAGE_TAG)
      # Ensure kaniko runs as root, "securityContext" is required for platforms like OpenShift.
      securityContext:
        runAsUser: 0
