apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-teams-message
spec:
  description: >- 
    Send a message to the Microsoft Teams channel that is configured with the webhook URL.
  params:
    - name: MESSAGE
      type: string
      description: The markdown message to be sent
  steps:
    - name: send-message
      image: badouralix/curl-jq
      env:
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.teamsWebhookUrlSecret }}
              key: url
      script: |
        #!/bin/sh

        MESSAGE=$(printf "%s" "$(params.MESSAGE)" | awk '{printf "%s\n\n", $0}')

        jq -n --arg message "$MESSAGE" '{
          "type": "message",
          "attachments": [
            {
              "contentType": "application/vnd.microsoft.card.adaptive",
              "contentUrl": null,
              "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.2",
                "body": [
                  {
                    "type": "TextBlock",
                    "text": $message
                  }
                ]
              }
            }
          ]
        }' > "message.json"

        curl -X POST -H 'Content-Type: application/json' -d @message.json ${WEBHOOK_URL}