apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-infra-commit-push
  labels:
    {{- include "deploy-release.labels" . | nindent 4 }}
spec:
  params:
    - name: MESSAGE
      type: string
      description: The commit message
  workspaces:
    - name: source
      description: The workspace containing the source code to commit and push
  steps:
    - name: commit-and-push
      image: alpine/git
      workingDir: $(workspaces.source.path)
      env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.gitHubInfraCommitSecret }}
              key: username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.gitHubInfraCommitSecret }}
              key: password
      script: |
        #!/bin/sh
        set +x

        git config --global user.email "tekton-ci@example.com"
        git config --global user.name "tekton-ci"
        
        # remove https from the URL
        URL=$(echo {{ .Values.infraGitUrl | quote }} | sed 's/^https:\/\///')
        git remote set-url origin https://$GIT_USERNAME:$GIT_PASSWORD@$URL
        
        git add .
        git commit -m "$(params.MESSAGE)"
        git push