apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name:  {{ include "deploy-release.name" . }}
  labels:
    {{- include "deploy-release.labels" . | nindent 4 }}
spec:
  params:
    - name: COMPONENTS
      type: array
      description: Component to be released. 'frontend', 'backend'
    - name: VERSION
      type: string
      description: Semantic Version, z.B. "0.11.2"
    - name: IMAGE_TAG
      type: string
      description: The tag of the component image to deploy.
  workspaces:
    - name: source-pvc
  tasks:
    - name: copy-images
      params:
        - name: COMPONENTS
          value: $(params.COMPONENTS[*])
        - name: SOURCE_TAG
          value: $(params.IMAGE_TAG)
        - name: DESTINATION_TAG
          value: $(params.VERSION)
      taskRef:
        kind: Task
        name: skopeo
    - name: clone-infra
      params:
        - name: URL
          value: {{ .Values.infraGitUrl }}
        - name: BRANCH
          value: main
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: source
          workspace: source-pvc
    - name: update-version
      params:
        - name: COMPONENTS
          value: $(params.COMPONENTS[*])
        - name: VERSION
          value: $(params.VERSION)
      runAfter:
        - clone-infra
      taskRef:
        kind: Task
        name: update-infra-component-version
      workspaces:
        - name: source
          workspace: source-pvc
    - name: commit-push
      params:
        - name: BRANCH
          value: main
        - name: MESSAGE
          value: "Update components to v$(params.VERSION)"
      runAfter:
        - update-version
      taskRef:
        kind: Task
        name: git-infra-commit-push
      workspaces:
        - name: source
          workspace: source-pvc