apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.restartDeploymentRbacName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.restartDeploymentRbacName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.restartDeploymentRbacName }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.restartDeploymentRbacName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.restartDeploymentRbacName }}
    namespace: {{ .Release.Namespace }}