apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  labels:
    {{- include "common.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggers-eventlistener-binding
  labels:
    {{- include "common.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles