infraGitUrl: https://github.com/LucasG04/library-management-infra.git
frontend:
  gitUrl: https://github.com/LucasG04/library-management-frontend.git
  imageName: lucasg04/library-management-frontend
backend:
  gitUrl: https://github.com/LucasG04/library-management-backend.git
  imageName: lucasg04/library-management-backend
