global:
  frontend:
    imageTag: 0.0.2
    imagePullPolicy: IfNotPresent
  backend:
    imageTag: 0.0.2
    imagePullPolicy: IfNotPresent
  restartDeploymentRbacName: rbac-restart-deployment
  configmapAccessRbacName: configmap-access
