global:
  frontend:
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent
  backend:
    imageTag: 0.0.1
    imagePullPolicy: IfNotPresent

  restartDeploymentRbacName: rbac-restart-deployment
  configmapAccessRbacName: configmap-access
