apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.lastPolledRevisionRbacName }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.lastPolledRevisionRbacName }}-role
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.lastPolledRevisionRbacName }}-rolebinding
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.lastPolledRevisionRbacName }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.lastPolledRevisionRbacName }}-role
  apiGroup: rbac.authorization.k8s.io