apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "frontend.name" . }}-polling
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: polling-job
              volumeMounts:
                - name: polledrepos
                  mountPath: /repos
              image: rockylinux/rocky-toolbox:9
              env:
                - name: REPOURL
                  value: {{ .Values.repository.cloneUrl }}
                - name: REPOBRANCH
                  value: {{ .Values.global.frontend.ciBranch }}
                - name: EVENTLISTENER_SVC_URL
                  value: http://el-{{ include "frontend.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:8080
              command:
                - /bin/bash
              args:
                - -c
                - |
                  set -euo pipefail

                  # Trap to handle errors
                  trap 'echo "Error occurred at line $LINENO"; exit 1' ERR

                  # Logging function
                  log() {
                      local level="$1"
                      local message="$2"
                      echo "[$(date +'%Y-%m-%d %H:%M:%S')] [$level] $message"
                  }

                  # Check required environment variables
                  required_vars=(REPOURL REPOBRANCH EVENTLISTENER_SVC_URL)
                  for var in "${required_vars[@]}"; do
                      if [ -z "${!var:-}" ]; then
                          log "ERROR" "Environment variable $var is not set"
                          exit 1
                      fi
                  done

                  # Check for required commands
                  required_commands=(git curl)
                  for cmd in "${required_commands[@]}"; do
                      if ! command -v "$cmd" &> /dev/null; then
                          log "ERROR" "Required command '$cmd' not found"
                          exit 1
                      fi
                  done

                  # Load previous hash from ConfigMap
                  configmap_file="/etc/config/revision.sha256"
                  _prev_revision=""
                  if [ -f "${configmap_file}" ]; then
                      _prev_revision=$(cat "${configmap_file}")
                      log "INFO" "Loaded previous revision from ConfigMap: ${_prev_revision}"
                  else
                      log "INFO" "No previous revision found."
                  fi

                  # Get current revision
                  _current_revision=$(git ls-remote --heads "${REPOURL}" "${REPOBRANCH}" | awk '{print $1}')
                  log "INFO" "Current revision: ${_current_revision}"

                  # Compare revisions
                  if [ "${_current_revision}" != "${_prev_revision}" ]; then
                      log "INFO" "Changes detected. Current revision: ${_current_revision}, Previous revision: ${_prev_revision}"
                      echo -n "${_current_revision}" > next_revision.sha256

                      # Update ConfigMap with new revision
                      kubectl create configmap {{ include "frontend.name" . }}-last-polled-revision \
                          --from-file="revision.sha256=next_revision.sha256" \
                          --dry-run=client -o yaml | kubectl apply -f -

                      # Generate JSON data
                      _jsondata=$(printf '{
                          "revision": "%s",
                          "repository_url": "%s",
                          "repository_name": "%s",
                          "repository_branch": "%s"
                      }' "${_current_revision}" "${REPOURL}" "${REPONAME}" "${REPOBRANCH}")

                      log "INFO" "Triggering pipeline with data: ${_jsondata}"

                      # Trigger the pipeline
                      response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
                          -H 'Content-Type: application/json' \
                          -d "${_jsondata}" "${EVENTLISTENER_SVC_URL}")

                      # Check response if http code is not 2xx
                      if [[ ${response} != 2* ]]; then
                          log "ERROR" "Failed to trigger pipeline. HTTP status code: ${response}"
                          exit 1
                      fi

                      log "INFO" "Pipeline triggered successfully."
                  else
                      log "INFO" "No changes detected. No action needed."
                  fi
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: {{ include "frontend.name" . }}-last-polled-revision
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.name" . }}-last-polled-revision
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  revision.sha256: ""