apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-exec
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  params:
    - name: IMAGE
      type: string
      description: The Docker image to use
      default: node:22
    - name: COMMAND
      type: string
      description: The npm command to run
  workspaces:
    - name: source
      description: The workspace containing the npm project
    - name: cache
      description: The workspace for the npm cache
      optional: true
  steps:
      - name: run-npm-command
        image: $(params.IMAGE)
        workingDir: $(workspaces.source.path)
        script: |
          #!/bin/sh
          # check if the cache is mounted
          if [ "$(workspaces.cache.bound)" = "true" ]; then
            echo "Cache found, using it..."
            npm config set cache $(workspaces.cache.path)/.npm
          fi
          
          npm $(params.COMMAND)