apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-exec
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  params:
    - name: image
      type: string
      description: The Docker image to use
      default: node:22
    - name: command
      type: string
      description: The npm command to run
  workspaces:
    - name: source
      description: The workspace containing the npm project
    - name: cache
      description: The workspace for the npm cache
      optional: true
  steps:
      - name: run-npm-command
        image: $(params.image)
        workingDir: $(workspaces.source.path)
        env:
          - name: CI
            value: "true"
        script: |
          #!/bin/sh
          # check if the cache is mounted
          if [ -d ${WORKSPACE_CACHE} ]; then
            echo "Cache found, using it..."
            npm config set cache ${WORKSPACE_CACHE}/.npm
          fi
          
          npm $(params.command)