apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frontend.name" . }}-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 4Gi
  volumeName: shared-pv